# Generated by Django 3.0.10 on 2021-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='architecture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='hostname',
            field=models.TextField(verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='large_file_chunk_size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='large_file_threshold',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='max_cores',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='max_cores_per_job',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='max_memory_per_core',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='max_walltime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.TextField(verbose_name='Name of Cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='scheduler_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='time_cmd',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, verbose_name='Name of Project'),
        ),
    ]
