# Generated by Django 3.0.10 on 2021-01-21 15:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210121_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='arguments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
