# Generated by Django 3.0.10 on 2021-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name of Key Pair'),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='private_key_encrypted',
            field=models.TextField(null=True, verbose_name='Encrypted private key for ssh connection'),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key',
            field=models.TextField(null=True, verbose_name='Public key for ssh connection'),
        ),
    ]
