# Generated by Django 3.0.10 on 2021-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20210121_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedkey',
            name='username',
            field=models.TextField(verbose_name='Username for cluster user'),
        ),
    ]
